version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hello-spring-boot-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - hello-spring-boot-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: hello-spring-boot-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      - hello-spring-boot-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  hello-spring-boot-network:

volumes:
  postgres_data:
